version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  db:
    image: postgres:latest
    container_name: smol-db
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
  nocodb: 
    image: "nocodb/nocodb:latest"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"
  # core:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - API_PORT=${API_PORT}
  #     - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
  #     - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
  #   ports:
  #     - 8000:8000
volumes:
  redis_volume_data:
  redis_insight_volume_data:
